<!DOCTYPE html>

<html>

	<head>
		<title>Developers Team</title>
		<meta charset="UTF-8">
		<link rel="icon" type="image/x-icon" href="images/user-gear.svg">
		<link rel="stylesheet" href="stylesheets/tuHeader.css">
		<link rel="stylesheet" href="stylesheets/tuMainCr.css">
	</head>

	<body>

			<header>

				<nav>
					<div id="Menu">
						<a class="Menu" href="/">User</a>
						<a class="Menu" href="/task/">Task</a>
						<a class="Menu" href="/list/">List</a>
					</div>
				</nav>

				<div id="AppName"><h1 id="AppName">Task Updater</h1></div>

			</header>

			<main>

				<div>
					<h3>Create user</h3>
				</div>

				<div id="Columns">
					<div id="c1">
						<form action="/draft/" method="post">
							<input type="text" name="user" placeholder="Full name">
							<button type="submit">Create</button>
						</form>
					</div>

					<div id="c2">
					</div>

				</div>

			</main>

	</body>

</html>

