<!DOCTYPE html>

<html>

	<head>
		<title>Developers Team</title>
		<meta charset="UTF-8">
		<link rel="icon" type="image/x-icon" href="../icons/user-gear.png">
		<link rel="stylesheet" href="../CSS/tuHeader.css">
		<link rel="stylesheet" href="../CSS/tuMainListV.css">
	</head>

	<body>

			<header>

				<nav>
					<div id="Menu">
						<a class="Menu" href="/draft/">User</a>
						<a class="Menu" href="/draft/task/">Task</a>
						<a class="Menu" href="/draft/list/">List</a>
					</div>
				</nav>

				<div id="AppName">
					<h1>Task Updater</h1>
				</div>

			</header>

			<main>

				<div id="Label"> <h3>Listing</h3> </div>

				<div id="Column">
					<p>Item 1</p>
					<p>Item 2</p>
					<p>...</p>
					<p>Item n<p>
				</div>

			</main>

	</body>

</html>

