<!DOCTYPE html>

<html>

  <head>
    <title>Developers Team</title>
    <meta charset="UTF-8">
    <link rel="icon" type="image/x-icon" href="../images/user-gear.svg">
    <link rel="stylesheet" href="../stylesheets/tu.css">
  </head>

  <body class="max-w-screen-xl m-auto flex flex-col">

<!-- Header -->

    <header class="mt-2.5 mr-0 mb-0 ml-0" >

      <nav class="p-1 bg-LightBlue Arial sans-serif text-base font-bold">
        <a class="pt-0 pr-2.5 pb-0 pl-1 text-Navy no-underline hover:no-underline hover:bg-Gold" href="/create/">Create</a>
        <a class="pt-0 pr-2.5 pb-0 pl-1 text-Navy no-underline hover:no-underline hover:bg-Gold" href="/UD/">Update/Delete</a>
        <a class="pt-0 pr-2.5 pb-0 pl-1 text-Navy no-underline hover:no-underline hover:bg-Gold" href="/list/">List</a>
      </nav>

      <div class="bg-MidnightBlue text-BlanchedAlmond flex justify-center">
        <h1 class="p-1 text-4xl font-bold">Task Updater</h1>
      </div>

    </header>

<!-- Header -->

    <main class="pt-2.5 pr-1 pb-2.5 pl-2.5 bg-LightBlue text-Navy flex flex-col">

<!-- Labels -->

      <div class="flex flex-row">
        <div class="m-1 text-xl font-bold basis-2/4 flex justify-start">        <h3>Create User</h3></div>
        <div class="m-1 text-xl font-bold basis-2/4 flex justify-start visible"><h3>Create Task</h3></div>
      </div>

<!-- Labels -->

      <div class="flex flex-row">

<!-- Column 1 -->

        <div class="m-1 bg-BurlyWood basis-2/4 flex justify-center">
          <div class="m-2.5 p-2.5 flex flex-column">

            <form action="/create/" method="post">

<!-- Text input 1 -->

              <div class="flex flex-row"> 
                <div class="mt-0 mr-0 mb-2.5 ml-0 bg-white border-2 border-solid border-Navy placeholder-Gray"> 
                  <input type="text" name="user" placeholder="Full name" class="w-full">
                </div>
                <div class="pt-0 pr-0 pb-0 pl-1 text-red-500 font-bold">
                  <?php echo $GLOBALS ['usrErr']; ?>
                </div>
              </div>

<!-- Text input 1 -->

<!-- Submit button 1 -->

              <div class="border border-none bg-Navy text-white text-center hover:bg-MediumBlue">
                <button type="submit" name="crtUser" value="crtUser" class="w-full">Create User</button>
              </div>

<!-- Submit button 1 -->

            </form>
          </div>
        </div>

<!-- Column 1 -->

<!-- Column 2 -->

        <div class="m-1 bg-BurlyWood basis-2/4 flex justify-center visible">
          <div class="m-2.5 p-2.5 flex flex-column">
            <form action="/create/">

<!-- Text input 2 -->

              <div class="flex flex-row justify-start"> 
                <div class="mt-0 mr-0 mb-2.5 ml-0 bg-white border-2 border-solid border-Navy placeholder-Gray">
                  <input type="text" name="user" placeholder="Full name" class="w-full">
                </div>
                <div class="pt-0 pr-0 pb-0 pl-1 text-red-500 font-bold">
                  <?php echo $GLOBALS ['tusErr']; ?>
                </div>
              </div>

              <div class="flex flex-row justify-start"> 
                <div class="mt-0 mr-0 mb-2.5 ml-0 bg-white border-2 border-solid border-Navy placeholder-Gray">
                  <input type="text" name="description" placeholder="Description" class="w-full">
                </div>
                <div class="pt-0 pr-0 pb-0 pl-1 text-red-500 font-bold">
                  <?php echo $GLOBALS ['desErr']; ?>
                </div>
              </div>

              <div class="flex flex-row justify-start"> 
                <div class="mt-0 mr-0 mb-2.5 ml-0 bg-white border-2 border-solid border-Navy placeholder-Gray">
                  <input type="text" name="dStart" placeholder="Start YYYY-mm-dd hh:mm:ss" class="w-full">
                </div>
                <div class="pt-0 pr-0 pb-0 pl-1 text-red-500 font-bold">
                  <?php echo $GLOBALS ['dstErr']; ?>
                </div>
              </div>

              <div class="flex flex-row justify-start"> 
                <div class="mt-0 mr-0 mb-2.5 ml-0 bg-white border-2 border-solid border-Navy placeholder-Gray">
                  <input type="text" name="dFinish" placeholder="Finish YYYY-mm-dd hh:mm:ss" class="w-full">
                </div>
                <div class="pt-0 pr-0 pb-0 pl-1 text-red-500 font-bold">
                  <?php echo $GLOBALS ['dfiErr']; ?>
                </div>
              </div>

<!-- Text input 2 -->

<!-- Radio buttons 2 -->

              <div class="flex flex-row justify-start"> 
                <div class="pt-0 pr-0 pb-1 pl-0 flex flex-row">
                  <div class"m-1 text-sm">
                    <label>Pending</label>
                    <input type="radio" name="status" value="pending" class="m-1">
                  </div>
                  <div class"m-1 text-sm">
                    <label>Running</label>
                    <input type="radio" name="status" value="running" class="m-1">
                  </div>
                  <div class"m-1 text-sm">
                    <label>Finished</label>
                    <input type="radio" name="status" value="finished" class="m-1">
                  </div>
                </div>
                <div class="pt-0 pr-0 pb-0 pl-1 text-red-500 font-bold">
                  <?php echo $GLOBALS ['staErr']; ?>
                </div>
              </div>

<!-- Radio buttons 2 -->

<!-- Submit button 2 -->

              <div class="border-none bg-Navy text-white text-center hover:bg-MediumBlue">
                <button type="submit" name="crtTask" value="crtTask" class="w-full">Create Task</button>
              </div>

<!-- Submit button 2 -->

            </form>

          </div>
        </div>

<!-- Column 2 -->

      </div>
    </main>
  </body>
</html>

