<!DOCTYPE html>

<html>

	<head>
		<title>Developers Team</title>
		<meta charset="UTF-8">
		<link rel="icon" type="image/x-icon" href="../images/user-gear.svg">
		<link rel="stylesheet" href="../stylesheets/tu.css">
	</head>

	<body class="max-w-screen-xl m-auto flex flex-col">

			<header class="mt-2.5 mr-0 mb-0 ml-0" >

  			<nav class="p-1 bg-LightBlue Arial sans-serif text-base font-bold">
          <a class="pt-0 pr-2.5 pb-0 pl-1 text-Navy no-underline hover:no-underline hover:bg-Gold" href="/">User</a>
          <a class="pt-0 pr-2.5 pb-0 pl-1 text-Navy no-underline hover:no-underline hover:bg-Gold" href="/task/">Task</a>
          <a class="pt-0 pr-2.5 pb-0 pl-1 text-Navy no-underline hover:no-underline hover:bg-Gold" href="/list/">List</a>
        </nav>

				<div class="bg-MidnightBlue text-BlanchedAlmond flex justify-center">
          <h1 class="p-1 text-4xl font-bold">Task Updater</h1>
				</div>

			</header>

			<main class="pt-2.5 pr-1 pb-2.5 pl-2.5 bg-LightBlue text-Navy flex flex-col">

				<div class="m-1 text-xl font-bold"> <h3>Listing</h3> </div>

				<div class="m-2.5 pt-1 pr-1 pb-1 pl-2.5 bg-BurlyWood">
					<p>Item 1</p>
					<p>Item 2</p>
					<p>...</p>
					<p>Item n<p>
				</div>

			</main>

	</body>

</html>

