<!DOCTYPE html>

<html>

  <head>
    <title>Developers Team</title>
    <meta charset="UTF-8">
    <link rel="icon" type="image/x-icon" href="../images/user-gear.svg">
    <link rel="stylesheet" href="../stylesheets/tu.css">
  </head>

  <body class="max-w-screen-xl m-auto flex flex-col">

    <header class="mt-2.5 mr-0 mb-0 ml-0" >

      <nav class="p-1 bg-LightBlue Arial sans-serif text-base font-bold">
        <a class="pt-0 pr-2.5 pb-0 pl-1 text-Navy no-underline hover:no-underline hover:bg-Gold" href="/">User</a>
        <a class="pt-0 pr-2.5 pb-0 pl-1 text-Navy no-underline hover:no-underline hover:bg-Gold" href="/task/">Task</a>
        <a class="pt-0 pr-2.5 pb-0 pl-1 text-Navy no-underline hover:no-underline hover:bg-Gold" href="/list/">List</a>
      </nav>

      <div class="bg-MidnightBlue text-BlanchedAlmond flex justify-center">
        <h1 class="p-1 text-4xl font-bold">Task Updater</h1>
      </div>

    </header>

    <main class="pt-2.5 pr-1 pb-2.5 pl-2.5 bg-LightBlue text-Navy flex flex-col">

      <div class="flex flex-row">
        <div class="m-1 text-xl font-bold basis-2/4 flex justify-start">        <h3>Create Task</h3></div>
        <div class="m-1 text-xl font-bold basis-2/4 flex justify-start visible"><h3>Check Task</h3></div>
      </div>

      <div class="flex flex-row">
        <div class="m-1 bg-BurlyWood basis-2/4 flex justify-center">
          <div class="m-2.5 p-2.5 flex flex-column">

            <form action="">

              <div class="flex flex-row justify-start"> 
                <div class="mt-0 mr-0 mb-2.5 ml-0 bg-white border-2 border-solid border-Navy placeholder-Gray">
                  <input type="text" name="user" placeholder="Full name" class="w-full">
                </div>
                <div class="pt-0 pr-0 pb-0 pl-1 text-red-500 font-bold">
                  <?php echo $GLOBALS ['usrErr']; ?>
                </div>
              </div>

              <div class="flex flex-row justify-start"> 
                <div class="mt-0 mr-0 mb-2.5 ml-0 bg-white border-2 border-solid border-Navy placeholder-Gray">
                  <input type="text" name="description" placeholder="Description" class="w-full">
                </div>
                <div class="pt-0 pr-0 pb-0 pl-1 text-red-500 font-bold">
                  <?php echo $GLOBALS ['desErr']; ?>
                </div>
              </div>

              <div class="flex flex-row justify-start"> 
                <div class="mt-0 mr-0 mb-2.5 ml-0 bg-white border-2 border-solid border-Navy">
                  <input type="datetime-local" name="dStart" placeholder="Start date" class="w-full">
                </div>
                <div class="pt-0 pr-0 pb-0 pl-1 text-red-500 font-bold">
                  <?php echo $GLOBALS ['dstErr']; ?>
                </div>
              </div>

              <div class="flex flex-row justify-start"> 
                <div class="mt-0 mr-0 mb-2.5 ml-0 bg-white border-2 border-solid border-Navy">
                  <input type="datetime-local" name="dFinish" placeholder="Finish date" class="w-full">
                </div>
                <div class="pt-0 pr-0 pb-0 pl-1 text-red-500 font-bold">
                  <?php echo $GLOBALS ['dfiErr']; ?>
                </div>
              </div>

              <div class="flex flex-row justify-start"> 
                <div class="pt-0 pr-0 pb-1 pl-0 flex flex-row">
                  <div class"m-1 text-sm">
                    <label>Pending</label>
                    <input type="radio" name="status" value="pending" class="m-1">
                  </div>
                  <div class"m-1 text-sm">
                    <label>Running</label>
                    <input type="radio" name="status" value="running" class="m-1">
                  </div>
                  <div class"m-1 text-sm">
                    <label>Finished</label>
                    <input type="radio" name="status" value="finished" class="m-1">
                  </div>
                </div>
                <div class="pt-0 pr-0 pb-0 pl-1 text-red-500 font-bold">
                  <?php echo $GLOBALS ['staErr']; ?>
                </div>
              </div>

              <div class="border-none bg-Navy text-white text-center hover:bg-MediumBlue">
                <button type="submit" name="task" value="task" class="w-full">Create</button>
              </div>

            </form>

          </div>
        </div>

        <div class="m-1 bg-BurlyWood basis-2/4 flex justify-center visible">
          <div class="m-2.5 p-2.5 flex flex-column">
            <form action="">
              <div class="mt-0 mr-0 mb-2.5 ml-0 bg-white border-2 border-solid border-Navy placeholder-Gray">
                <input type="text" name="user" placeholder="Full name" class="w-full">
              </div>
              <div class="mt-0 mr-0 mb-2.5 ml-0 bg-white border-2 border-solid border-Navy placeholder-Gray">
                <input type="text" name="description" placeholder="Description" class="w-full">
              </div>
              <div class="mt-0 mr-0 mb-2.5 ml-0 bg-white border-2 border-solid border-Navy">
                <input type="datetime-local" name="dStart" placeholder="Start date" class="w-full">
              </div>
              <div class="mt-0 mr-0 mb-2.5 ml-0 bg-white border-2 border-solid border-Navy">
                <input type="datetime-local" name="dFinish" placeholder="Finish date" class="w-full">
              </div>

              <div class="pt-0 pr-0 pb-1 pl-0 flex flex-row">
                <div class"m-1 text-sm">
                  <label>Pending</label>
                  <input type="radio" name="chkStatus" value="pending" class="m-1">
                </div>
                <div class"m-1 text-sm">
                  <label>Running</label>
                  <input type="radio" name="chkStatus" value="running" class="m-1">
                </div>
                <div class"m-1 text-sm">
                  <label>Finished</label>
                  <input type="radio" name="chkStatus" value="finished" class="m-1">
                </div>
              </div>
              <div class="border-none bg-Navy text-white text-center hover:bg-MediumBlue">
                <button type="submit" class="w-full">Check</button>
              </div>
            </form>

          </div>
        </div>
      </div>

    </main>
  </body>
</html>

